// decryptData.js
// This matches your Android "BuildConfig.ENCRYPTION_KEY"
const SECRET_KEY_STRING = "NxM1rr0r_D3f4ult_K3y_Ch4ng3_M3!";
/**
 * Converts the raw string key into a CryptoKey usable by the Web Crypto API
 */
async function importKey() {
  const encoder = new TextEncoder();
  const rawKeyData = encoder.encode(SECRET_KEY_STRING);
  
  // AES-256 requires exactly 32 bytes.
  // We pad with 0s if the string is shorter to maintain 256-bit length.
  const keyData = new Uint8Array(32);
  keyData.set(rawKeyData.slice(0, 32));
  
  return await window.crypto.subtle.importKey(
    "raw",
    keyData,
    { name: "AES-GCM" },
    false, // whether the key is extractable
    ["decrypt"]
  );
}
/**
 * Decrypts a Base64 encoded string generated by the Notification Manager app.
 * @param {string} base64Payload - The encrypted string from Firebase (e.g. notification.content)
 * @returns {string} - The original plaintext
 */
export async function decryptData(base64Payload) {
  if (!base64Payload) return "";
  
  try {
    // 1. Decode Base64 string to a Uint8Array
    const binaryString = atob(base64Payload);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
    }
    // 2. The Android app puts the 12-byte IV at the very beginning of the payload
    const iv = bytes.slice(0, 12);
    
    // 3. The remaining bytes are the Ciphertext
    const ciphertext = bytes.slice(12);
    // 4. Decrypt using the native Web Crypto API
    const key = await importKey();
    const decryptedBuffer = await window.crypto.subtle.decrypt(
      {
        name: "AES-GCM",
        iv: iv
      },
      key,
      ciphertext
    );
    // 5. Convert the decrypted binary buffer back into UTF-8 text
    const decoder = new TextDecoder();
    return decoder.decode(decryptedBuffer);
    
  } catch (error) {
    console.error("Decryption failed for payload:", error);
    return "[Decryption Failed]";
  }
}
